### ISSUE TITLE
🐛 - Gitlab LDAP bindDN and base not fully qualified

### ISSUE THREAD

**Issue by eformat** [rht-labs/enablement-framework#118] opened 2022-05-19 01:18 UTC
when deploying the base tl500 helm chart - the ldap creds for gitlab are automatically created by looking up the OAuth identity provider

this is done in the _helpers.tpl code

BUT .. we just had an instance where the "bind_dn" and "base" in the GITLAB_OMNIBUS_CONFIG was set wrong ! here are the screenshots:

![Screenshot from 2022-05-19 10-22-07](https://user-images.githubusercontent.com/712608/169181263-899f6195-41c9-46be-b911-f99dd0af0149.png)

![Screenshot from 2022-05-19 10-58-25](https://user-images.githubusercontent.com/712608/169181271-d8ef5f39-30ec-4b8e-b819-8a2bf362502b.png)

They should be:

```bash
'bind_dn' => 'uid=ldap-sa,cn=users,cn=accounts,dc=rht-labs,dc=com',
'base' => 'cn=accounts,dc=rht-labs,dc=com'
```

So, the lookup is failing somehow.

I have noticed similar behavior in another chart where you NEED to escape the ',' e.g.

```
helm upgrade --install my-chart \
--set ldap_bind_dn="uid=ldap_admin\\,cn=users\\,cn=accounts\\,dc=redhatlabs\\,dc=dev"
```

Anyway .. this needs looking into root cause. It doesn't happen in every deployment, this is the first i have seen it in the real !

**Comment by jfilipcz** [comment] 2022-05-19 08:35
Root cause was simple - since I've started to works with those helm-charts, we had some issues with gitlab integration (with configuration set through the helper), and resorted back to using values set manually:)

**Comment by jfilipcz** [comment] 2022-05-19 08:36
I will give it another test on my private cluster, and if all works out  we can close the issue (possibly with a documentation update)

**Comment by jfilipcz** [comment] 2022-05-19 11:52
Tests confirmed all is working fine.

**Closed** 2022-05-19 12:06 UTC

**Comment by eformat** [comment] 2022-05-19 22:51
@jfilipcz thanks for confirming ! OK .. yeah \\, escaping needed :) if setting values for ldap 

the lookup logic works fine though, has not broken ever as far as i can tell
